# Generated by Django 3.2.23 on 2023-12-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entree', '0002_alter_entrees_texte'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('passw', models.CharField(max_length=50)),
            ],
        ),
    ]
