# Generated by Django 3.2.23 on 2023-12-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entree', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
