# Generated by Django 3.2.23 on 2023-12-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entree', '0007_alter_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrees',
            name='nbr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entrees',
            name='us_id',
            field=models.IntegerField(default=0),
        ),
    ]
