# Generated by Django 3.2.23 on 2023-12-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entree', '0008_auto_20231212_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='us_id',
            field=models.IntegerField(default=0),
        ),
    ]
